[package]
authors = ["tiany7 <yt2825@columbia.edu>"]
edition = "2021"
license = "MIT"
name = "proxy_server"
publish = false
version = "0.1.0"

[dependencies]
tonic = "0.11"
prost = "0.12"
tokio = { version = "1.0", features = ["rt-multi-thread", "macros", "sync", "time"] }
tokio-stream = "0.1"

async-stream = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
rand = "0.7"
chrono = "0.4"

binance-async = "0.3.0"
anyhow = "1.0"
fehler = { version = "1.0.0-alpha.2" }
env_logger = "0.9"
futures = "0.3"
rust_decimal = "1.10.0"
clap = "3.0"
arrow = "5.0.0"
lz4 = "1.23.1"



[build-dependencies]
tonic-build = "0.11"




[[bin]]
name = "websocket_server"
path = "binance_data/websocket.rs"

[[bin]]
name = "binance_client"
path = "client/binance_client.rs"

[[bin]]
name = "binance_server"
path = "binance_data/binance_grpc_server.rs"

[[bin]]
name = "pipeline_server"
path = "binance_data_pipeline/pipeline_main.rs"


serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"


members = [
    "binance_data",
    "binance_data_pipeline",
]
